### ISSUE TITLE
Internal server error on object cutter inference API

### ISSUE THREAD

**Issue by kram254** [finegrain-ai/refiners#459]
I have been trying to use your refiners object cutter model on an App just for testing and I have not been able to get a response from the API endpoint, I keep getting internal server error
![image](https://github.com/user-attachments/assets/c71f5c7d-cfba-4d57-bb5f-3f8b66f1d3f1)

**Comment by Laurent2916** [comment]
Hi @kram254!
There is no `/predict` endpoint on the space's API. The endpoints you should be hitting are `process_bbox` or `process_prompt`, you can see their documentation by clicking the "Use via API" at the bottom of the space.
