### ISSUE TITLE
Documentation way too vague

### ISSUE THREAD

**Issue by JuvenileLocksmith** [finegrain-ai/refiners#464]
You will need lots of vram and disk space. Come on. Nothing is communicated clearly. Everything is partially said. Given this a new implementation, it would be ideal if there we clear instructions to get things going,. So frustrating

**Comment by catwell** [comment]
Hello!

Actually [the documentation you are referring to](https://refine.rs/getting-started/recommended/#converting-weights) is outdated with [the last PR merged](https://github.com/finegrain-ai/refiners/pull/462). The fact that users had to convert weights was a problem and we now [publish the converted weights in the Refiners Hugging Face organization](https://huggingface.co/refiners).

This means that unless you are porting a new model you can just use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download) to get the weights and not care about conversion. We will update the documentation to illustrate this shortly.
